con:
  token: '' # Discord bot token
# vote:
#   webhook: # webhook port
#   auth: # webhook auth (from vote site)

mysql: # MySQL database credentials
  host: ''
  user: ''
  password: ''
  database: ''

dashboard:
  port: 6969
  usingCustomDomain: false
  domain: '' # Dashboard domain
  clientSecret: '' # Client Secret from dev panel
  secret: '' # Idfk it's a secret put it as a secret
  colors: ['#ffffff', '#000000'] # colors for dashboard background