con:
  token: '' # Discord bot token
# vote:
#   webhook: # webhook port
#   auth: # webhook auth (from vote site)

mysql: # MySQL database credentials
  host: ''
  user: ''
  password: ''
  database: ''